'use client'

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { store } from "@/features/store";
import { Provider } from 'react-redux';

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Todo App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-3xl mx-auto p-4">
          <Navbar></Navbar>
          <Provider store={store}>
            <div className="mt-8">
              {children}
            </div>
          </Provider>
        </div>
      </body>
    </html>
  );
}
